### ISSUE TITLE
组件引用

### ISSUE THREAD

**Issue by cheng11231456** [CullenNg/page-design#4]
如果我想引用私有组件，应该怎么办

**Comment by CullenNg** [comment]
@cheng11231456 
### 如果在现有组件上里面引用的话，可以在组件里面 import 引用就可以了
```
<script>
import a from './xxxxx'

export default {
    components: {
        a
    }
}
</script>
```

### 如果想自定义注册1个组件的话
1. 得参考 ```src/ui-component/``` 目录下的组件的代码结构，自行新增1个组件文件夹
2. 然后在 ```src/interface/get_component_list.json``` 和 ```src/interface/get_component_template_list.json``` 中添加对应的组件信息即可

目前关于这块的文档还没编写完毕哈，后续会补上详细的文档
